import type { Block } from '../types'

/** React Hooks 样例 — 与 threadmind_prd_v2.html / PRD v6 §1.6 对齐 */
export const MOCK_BLOCKS: Block[] = [
  {
    id: 'l1-hooks',
    level: 1,
    title: 'React Hooks',
    summary:
      'React 16.8 引入的函数，让函数组件使用状态与生命周期，无需 class。',
    collected: [],
    noteContent: '',
    isExpanded: true,
    parentId: null,
    order: 1000,
    createdAt: 1,
  },
  {
    id: 'l2-usestate',
    level: 2,
    title: 'useState',
    summary: '返回状态值与更新函数，调用更新函数触发重新渲染。',
    collected: [],
    noteContent: '',
    isExpanded: true,
    parentId: 'l1-hooks',
    order: 2000,
    createdAt: 2,
  },
  {
    id: 'l3-lazy-init',
    level: 3,
    title: '初始值惰性初始化',
    summary: '',
    collected: [],
    noteContent: '',
    isExpanded: false,
    parentId: 'l2-usestate',
    order: 3000,
    createdAt: 3,
  },
  {
    id: 'l3-rerender',
    level: 3,
    title: '更新触发重渲染',
    summary: '',
    collected: [],
    noteContent: '',
    isExpanded: false,
    parentId: 'l2-usestate',
    order: 4000,
    createdAt: 4,
  },
  {
    id: 'l2-useeffect',
    level: 2,
    title: 'useEffect',
    summary: '渲染后执行副作用，依赖数组控制执行时机。',
    collected: [],
    noteContent: '',
    isExpanded: true,
    parentId: 'l1-hooks',
    order: 5000,
    createdAt: 5,
  },
  {
    id: 'l3-deps',
    level: 3,
    title: '依赖数组',
    summary: '为空只执行一次，填入变量则该变量变化时重新执行。',
    collected: [],
    noteContent: '',
    isExpanded: true,
    parentId: 'l2-useeffect',
    order: 6000,
    createdAt: 6,
  },
  {
    id: 'l1-context',
    level: 1,
    title: 'useContext',
    summary: '',
    collected: [],
    noteContent: '',
    isExpanded: false,
    parentId: null,
    order: 7000,
    createdAt: 7,
  },
]
